// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: proto/core.proto

package corepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          string                 `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemRequest) Reset() {
	*x = ItemRequest{}
	mi := &file_proto_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemRequest) ProtoMessage() {}

func (x *ItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemRequest.ProtoReflect.Descriptor instead.
func (*ItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_proto_rawDescGZIP(), []int{0}
}

func (x *ItemRequest) GetItem() string {
	if x != nil {
		return x.Item
	}
	return ""
}

type ItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemResponse) Reset() {
	*x = ItemResponse{}
	mi := &file_proto_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemResponse) ProtoMessage() {}

func (x *ItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemResponse.ProtoReflect.Descriptor instead.
func (*ItemResponse) Descriptor() ([]byte, []int) {
	return file_proto_core_proto_rawDescGZIP(), []int{1}
}

func (x *ItemResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_core_proto protoreflect.FileDescriptor

const file_proto_core_proto_rawDesc = "" +
	"\n" +
	"\x10proto/core.proto\x12\x04core\"!\n" +
	"\vItemRequest\x12\x12\n" +
	"\x04item\x18\x01 \x01(\tR\x04item\"&\n" +
	"\fItemResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2;\n" +
	"\x04Core\x123\n" +
	"\n" +
	"ItemLookup\x12\x11.core.ItemRequest\x1a\x12.core.ItemResponseB!Z\x1fgo-core-service/internal/corepbb\x06proto3"

var (
	file_proto_core_proto_rawDescOnce sync.Once
	file_proto_core_proto_rawDescData []byte
)

func file_proto_core_proto_rawDescGZIP() []byte {
	file_proto_core_proto_rawDescOnce.Do(func() {
		file_proto_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_core_proto_rawDesc), len(file_proto_core_proto_rawDesc)))
	})
	return file_proto_core_proto_rawDescData
}

var file_proto_core_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_core_proto_goTypes = []any{
	(*ItemRequest)(nil),  // 0: core.ItemRequest
	(*ItemResponse)(nil), // 1: core.ItemResponse
}
var file_proto_core_proto_depIdxs = []int32{
	0, // 0: core.Core.ItemLookup:input_type -> core.ItemRequest
	1, // 1: core.Core.ItemLookup:output_type -> core.ItemResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_core_proto_init() }
func file_proto_core_proto_init() {
	if File_proto_core_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_core_proto_rawDesc), len(file_proto_core_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_core_proto_goTypes,
		DependencyIndexes: file_proto_core_proto_depIdxs,
		MessageInfos:      file_proto_core_proto_msgTypes,
	}.Build()
	File_proto_core_proto = out.File
	file_proto_core_proto_goTypes = nil
	file_proto_core_proto_depIdxs = nil
}
